// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0yKmjzFrIa2sTQgUBuJ3GykOSeh9ZX9Y',
    appId: '1:73130736559:web:5f1421b3118422ffdd8d5a',
    messagingSenderId: '73130736559',
    projectId: 'stem-18d55',
    authDomain: 'stem-18d55.firebaseapp.com',
    storageBucket: 'stem-18d55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCLXEKf6ZUcLgdipSZQ1iaF-pzyhNHr-k',
    appId: '1:73130736559:android:9485d0ce4a0e566fdd8d5a',
    messagingSenderId: '73130736559',
    projectId: 'stem-18d55',
    storageBucket: 'stem-18d55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo6f32K86td-2rRnor0W4BdCBUAeFjfrw',
    appId: '1:73130736559:ios:91dfb46f6b08c874dd8d5a',
    messagingSenderId: '73130736559',
    projectId: 'stem-18d55',
    storageBucket: 'stem-18d55.firebasestorage.app',
    iosBundleId: 'com.example.stem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo6f32K86td-2rRnor0W4BdCBUAeFjfrw',
    appId: '1:73130736559:ios:91dfb46f6b08c874dd8d5a',
    messagingSenderId: '73130736559',
    projectId: 'stem-18d55',
    storageBucket: 'stem-18d55.firebasestorage.app',
    iosBundleId: 'com.example.stem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0yKmjzFrIa2sTQgUBuJ3GykOSeh9ZX9Y',
    appId: '1:73130736559:web:f15507a701325d21dd8d5a',
    messagingSenderId: '73130736559',
    projectId: 'stem-18d55',
    authDomain: 'stem-18d55.firebaseapp.com',
    storageBucket: 'stem-18d55.firebasestorage.app',
  );
}
