name: stem
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.20
  
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  google_fonts: ^6.2.1
  badges: ^3.1.2
  get: ^4.6.6
  font_awesome_flutter: ^10.8.0
  flutter_inset_box_shadow: ^1.0.8
  url_launcher: ^6.3.1
  lottie: ^3.1.3
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1
  firebase_core: ^3.7.0
  firebase_vertexai: ^1.0.2
  flutter_shake_animated: ^0.0.5
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  # cloud_functions: ^5.1.4
  # cloud_firestore: ^5.4.5
  # firebase_auth: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/quiz/
    - assets/data/math_fact.json
    - assets/lottie/


flutter_icons:
  android: true  # Add icons for Android
  ios: true  # Add icons for iOS
  image_path: "assets/icons/icon.png"  
  
  # fonts:
  #   - family: Lora
  #     fonts:
  #       - asset: fonts/Lora-Regular.ttf
  #       - asset: fonts/Lora-Italic.ttf
