// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD4Df_maFda-lVm2DGNF35S1n11sDFZfk',
    appId: '1:810027548183:web:f5c9d40649798cc212a652',
    messagingSenderId: '810027548183',
    projectId: 'fire-4f118',
    authDomain: 'fire-4f118.firebaseapp.com',
    storageBucket: 'fire-4f118.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXAuviC98sukaM7PU5kkDyT3uBmPEkfkk',
    appId: '1:810027548183:android:23c967bb0426337412a652',
    messagingSenderId: '810027548183',
    projectId: 'fire-4f118',
    storageBucket: 'fire-4f118.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQQqgetGmbeTAlFmmesb7Dk3KWeXURJSA',
    appId: '1:810027548183:ios:ecdef8b8d35e86f812a652',
    messagingSenderId: '810027548183',
    projectId: 'fire-4f118',
    storageBucket: 'fire-4f118.firebasestorage.app',
    iosBundleId: 'com.example.stem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQQqgetGmbeTAlFmmesb7Dk3KWeXURJSA',
    appId: '1:810027548183:ios:ecdef8b8d35e86f812a652',
    messagingSenderId: '810027548183',
    projectId: 'fire-4f118',
    storageBucket: 'fire-4f118.firebasestorage.app',
    iosBundleId: 'com.example.stem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD4Df_maFda-lVm2DGNF35S1n11sDFZfk',
    appId: '1:810027548183:web:e1a06260f9fa5fa912a652',
    messagingSenderId: '810027548183',
    projectId: 'fire-4f118',
    authDomain: 'fire-4f118.firebaseapp.com',
    storageBucket: 'fire-4f118.firebasestorage.app',
  );
}
